"""Independent Google Gemma template renders; downloads no tokenizer or weights.

UV_CACHE_DIR=/tmp/mference-uv-cache uv run --no-project --with jinja2==3.1.6 \
  --with tokenizers==0.22.2 Scripts/gemma_thinking_template_oracle.py
Optional --tokenizer /path/to/tokenizer.json verifies an installed vocabulary.
Output goes to stdout; expected fixtures are never regenerated by Swift tests.
"""
import argparse
import hashlib
import json
from pathlib import Path
import jinja2
from jinja2.sandbox import ImmutableSandboxedEnvironment
import tokenizers

root = Path(__file__).resolve().parents[1]
fixture = root / 'Tests/Mference/Core/Tokenization/Fixtures/GemmaThinkingTokenizer'
parser = argparse.ArgumentParser()
parser.add_argument('--tokenizer', type=Path, default=fixture / 'tokenizer.json')
args = parser.parse_args()
source = (fixture / 'chat_template.jinja').read_bytes()
digest = hashlib.sha256(source).hexdigest()
assert digest == 'ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4'
environment = ImmutableSandboxedEnvironment(trim_blocks=True, lstrip_blocks=True)
def fail(message):
    raise ValueError(message)
environment.globals['raise_exception'] = fail
render = environment.from_string(source.decode()).render
tokenizer = tokenizers.Tokenizer.from_file(str(args.tokenizer))
tool = {'type': 'function', 'function': {'name': 'lookup', 'description': 'Lookup',
        'parameters': {'type': 'object', 'properties': {'query': {'type': 'string'}},
                       'required': ['query']}}}
def call(identifier='call_1'):
    return {'id': identifier, 'type': 'function',
            'function': {'name': 'lookup', 'arguments': {'query': 'A'}}}
opening = [{'role': 'user', 'content': 'Lookup A'}]
tool_turn = {'role': 'assistant', 'content': None, 'reasoning_content': 'Need lookup.',
             'tool_calls': [call()]}
result = {'role': 'tool', 'content': 'Found A', 'tool_call_id': 'call_1'}
histories = {
    'single': [{'role': 'user', 'content': ' Hi '}],
    'history': [{'role': 'system', 'content': ' Be terse. '},
                {'role': 'user', 'content': 'A'},
                {'role': 'assistant', 'content': ' B ', 'reasoning_content': 'Check A.'},
                {'role': 'user', 'content': 'C'}],
    'tool_call': opening + [tool_turn],
    'tool_result': opening + [tool_turn, result],
    'tool_final': opening + [tool_turn, result,
                           {'role': 'assistant', 'content': 'Done.', 'reasoning_content': 'Checked.'}],
    'next_user': opening + [tool_turn, result,
                           {'role': 'assistant', 'content': 'Done.', 'reasoning_content': 'Checked.'},
                           {'role': 'user', 'content': 'Again'}],
    'repeated_tools': opening + [tool_turn, result,
                      {'role': 'assistant', 'content': None, 'reasoning_content': 'Again.',
                       'tool_calls': [call('call_2'), call('call_3')]},
                      {'role': 'tool', 'content': 'Second A', 'tool_call_id': 'call_2'},
                      {'role': 'tool', 'content': 'Third A', 'tool_call_id': 'call_3'}],
}
cases = []
for name, messages in histories.items():
    tools = [tool] if name not in ('single', 'history') else []
    for thinking in [False, True]:
        for preserve in [False, True]:
            for generate in [False, True]:
                text = render(messages=messages, tools=tools, bos_token='<bos>',
                              enable_thinking=thinking, preserve_thinking=preserve,
                              add_generation_prompt=generate)
                cases.append(dict(name=name, messages=messages, tools=tools,
                                  thinking=thinking, preserve=preserve, generate=generate,
                                  render=text, ids=tokenizer.encode(text, add_special_tokens=False).ids))
print(json.dumps(dict(template_sha256=digest, jinja=jinja2.__version__,
                      tokenizers=tokenizers.__version__, cases=cases), ensure_ascii=False, indent=2))
